apiVersion: v1
kind: Service
metadata:
    name: postgres-cluster-ip-service
spec:
    type: ClusterIP
    selector:
        component: postgres
    ports:
        - port: 5432
          targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
    name: django-cluster-ip-service
spec:
    type: ClusterIP
    selector:
        component: django
    ports:
        - port: 8000
          targetPort: 8000